from lib.reverse import reverse
from lib.copy import copy
from lib.duplication_contents import duplicateContents
from lib.replace_string import replaceString
from lib.pwd import pwd
from lib.cd import cd
from lib.ls import ls
from lib.whoami import whoami
from lib.exit import exit
from lib.cat import cat
from lib.rm import rm
